--------------------------------------LAB 10----------------------------------

CREATE TABLE STUDENT
(
	RNO INT,
	NAME VARCHAR(50),
	BRANCH VARCHAR(50)
)

INSERT INTO STUDENT VALUES
(101,'RAJU','CE'),
(102,'AMIT','CE'),
(103,'SANJAY','ME'),
(104,'NEHA','EC'),
(105,'MEERA','EE'),
(106,'MAHESH','ME')

CREATE TABLE RESULT
(
	RNO INT,
	SPI DECIMAL(4,2),
)

INSERT INTO RESULT VALUES
(101,8.8),
(102,9.2),
(103,7.6),
(104,8.2),
(105,7.0),
(107,8.9)

CREATE TABLE EMPLOYEE
(
	EMPLOYEENO VARCHAR(50),
	NAME VARCHAR(50),
	MANAGERNO VARCHAR(50)
)

INSERT INTO EMPLOYEE VALUES
('E01','TARUN',NULL),
('E02','ROHAN','E02'),
('E03','PRIYA','E01'),
('E04','MILAN','E03'),
('E05','JAY','E01'),
('E06','ANJANA','E04')

SELECT * FROM STUDENT

SELECT * FROM RESULT

SELECT * FROM EMPLOYEE

--1
SELECT * FROM STUDENT
CROSS JOIN 
RESULT

--2
SELECT STUDENT.RNO,NAME,BRANCH,SPI 
FROM STUDENT
LEFT OUTER JOIN
RESULT
ON STUDENT.RNO=RESULT.RNO
WHERE BRANCH='CE'

--3
SELECT STUDENT.RNO,NAME,BRANCH,SPI 
FROM STUDENT
LEFT OUTER JOIN
RESULT
ON STUDENT.RNO=RESULT.RNO
WHERE BRANCH!='EC'

--4
SELECT BRANCH,AVG(SPI)
FROM
STUDENT
INNER JOIN
RESULT
ON STUDENT.RNO=RESULT.RNO
GROUP BY BRANCH

--5
SELECT BRANCH,AVG(SPI)
FROM
STUDENT
INNER JOIN
RESULT
ON STUDENT.RNO=RESULT.RNO
GROUP BY BRANCH
ORDER BY AVG(SPI)

--6
SELECT AVG(SPI),BRANCH
FROM 
STUDENT
INNER JOIN 
RESULT
ON STUDENT.RNO=RESULT.RNO
WHERE BRANCH IN ('ME','CE')
GROUP BY BRANCH

--7
SELECT * FROM
STUDENT
LEFT OUTER JOIN
RESULT
ON STUDENT.RNO = RESULT.RNO

--8
SELECT * FROM
STUDENT
RIGHT OUTER JOIN
RESULT
ON STUDENT.RNO = RESULT.RNO

--9
SELECT * FROM
STUDENT
FULL OUTER JOIN
RESULT
ON STUDENT.RNO = RESULT.RNO

--10
SELECT E.NAME AS EMPLOYEENAME,M.NAME AS MANAGERNAME
FROM 
EMPLOYEE E
LEFT JOIN
EMPLOYEE M
ON E.MANAGERNO=M.EMPLOYEENO

SP_RENAME 'STUDENT','STUDENT_10'
SELECT * FROM STUDENT_10

---------------------------

CREATE TABLE CITY
(
	CITYID INT PRIMARY KEY,
	CITYNAME VARCHAR(50) UNIQUE,
	PINCODE VARCHAR(6),
	REMARKS VARCHAR(250)
)

INSERT INTO CITY VALUES
(1,'RAJKOT','360005','GOOD'),
(2,'SURAT','335009','VERY GOOD'),
(3,'BARODA','390001','AWESOME'),
(4,'JAMNAGAR','361003','SMART'),
(5,'JUNAGADH','362229','HISTORIC'),
(6,'MORVI','363641','CERAMIC')

SELECT * FROM CITY

CREATE TABLE VILLAGE
(
	VILLAGEID INT PRIMARY KEY,
	VILLAGENAME VARCHAR(50),
	CITYID INT FOREIGN KEY REFERENCES CITY(CITYID)
)

INSERT INTO VILLAGE VALUES
(101,'RAIYA',1),
(102,'MADHAPAR',1),
(103,'DODKA',3),
(104,'FALLA',4),
(105,'BHESAN',5),
(106,'DHORAJI',5)

SELECT * FROM VILLAGE

--1
SELECT VILLAGENAME,CITYNAME
FROM
VILLAGE
INNER JOIN
CITY 
ON CITY.CITYID=VILLAGE.CITYID
WHERE CITYNAME='RAJKOT'

--2
SELECT CITYNAME,VILLAGENAME,PINCODE
FROM
CITY
INNER JOIN
VILLAGE
ON CITY.CITYID=VILLAGE.CITYID

--3
SELECT CITYNAME
FROM 
CITY
LEFT OUTER JOIN
VILLAGE
ON CITY.CITYID=VILLAGE.CITYID
GROUP BY CITYNAME
HAVING COUNT(VILLAGENAME)>1

--4
SELECT CITYNAME
FROM CITY
LEFT OUTER JOIN
VILLAGE
ON CITY.CITYID=VILLAGE.CITYID
GROUP BY CITYNAME
HAVING COUNT(VILLAGENAME)=0

--5
SELECT COUNT(VILLAGE.VILLAGEID),CITYNAME
FROM CITY
LEFT OUTER JOIN
VILLAGE
ON CITY.CITYID=VILLAGE.CITYID
GROUP BY CITYNAME

--6
SELECT COUNT(CITYNAME),CITYNAME
FROM
CITY
INNER JOIN
VILLAGE
ON CITY.CITYID=VILLAGE.CITYID
GROUP BY CITYNAME
HAVING COUNT(VILLAGE.CITYID)>1