--------LAB 12--------

CREATE PROCEDURE INSERT__RECORDS
@RNO INT,
@NAME VARCHAR(50),
@BRANCH VARCHAR(50)
AS
INSERT INTO STUDENT_10
VALUES(
       @RNO,
       @NAME,
       @BRANCH
)

EXEC INSERT__RECORDS 101,'RAJU','CE'
EXEC INSERT__RECORDS 102,'AMIT','CE'


SELECT * FROM STUDENT_10


--1
CREATE PROCEDURE DISPLAY_ALL_RECORDS
AS
SELECT STUDENT_10.RNO,NAME,BRANCH,SPI
FROM
STUDENT_10
LEFT OUTER JOIN 
RESULT
ON STUDENT_10.RNO = RESULT.RNO 

EXEC DISPLAY_ALL_RECORDS

--2
CREATE PROCEDURE USER_GET_RNO
@RNO INT
AS
SELECT
STUDENT_10.RNO,NAME,BRANCH,SPI
FROM STUDENT_10
INNER JOIN
RESULT 
ON STUDENT_10.RNO=RESULT.RNO
WHERE STUDENT_10.RNO=@RNO

EXEC USER_GET_RNO 101

ALTER PROCEDURE USER_GET_RNO
@RNO INT
AS
SELECT
STUDENT_10.RNO,NAME,BRANCH,SPI
FROM STUDENT_10
LEFT OUTER JOIN
RESULT 
ON STUDENT_10.RNO=RESULT.RNO
WHERE STUDENT_10.RNO=@RNO

EXEC USER_GET_RNO 106

--3
CREATE PROCEDURE INSERT_RECORD
AS
INSERT INTO STUDENT_10 VALUES
(107,'RAJ','EE')

SELECT * FROM STUDENT_10

EXEC INSERT_RECORD

--4
CREATE PROCEDURE UPDATE_BRANCH_
AS
UPDATE STUDENT_10 SET BRANCH='EC' WHERE RNO=105

EXEC UPDATE_BRANCH_

SELECT * FROM STUDENT_10

--5
CREATE PROCEDURE DELETE_RECORD
AS
DELETE FROM STUDENT_10 WHERE RNO=103

EXEC DELETE_RECORD

SELECT * FROM STUDENT_10