--• Stored Procedures

--1. All tables Insert, Update & Delete
--INSERT
	--Department
		CREATE PROC PR_DEPARTMENT_INSERT
			@DEPARTMENTID	INT,
			@DEPARTMENTNAME VARCHAR(100)
		AS
		BEGIN
			INSERT INTO DEPARTMENT VALUES
			(@DEPARTMENTID,	
			 @DEPARTMENTNAME)
		END

		EXEC PR_DEPARTMENT_INSERT 1,'ADMIN'
		EXEC PR_DEPARTMENT_INSERT 2,'IT'
		EXEC PR_DEPARTMENT_INSERT 3,'HR'
		EXEC PR_DEPARTMENT_INSERT 4,'ACCOUNT'

		SELECT * FROM DEPARTMENT

	--DESIGNATION 
		CREATE PROC PR_DESIGNATION_INSERT
			@DESIGNATIONID		INT,
			@DESIGNATIONNAME	VARCHAR(100)
		AS
		BEGIN
			INSERT INTO DESIGNATION VALUES
			(@DESIGNATIONID,	
			 @DESIGNATIONNAME)
		END

		EXEC PR_DESIGNATION_INSERT 11,'JOBBER'
		EXEC PR_DESIGNATION_INSERT 12,'WELDER'
		EXEC PR_DESIGNATION_INSERT 13,'CLERK'
		EXEC PR_DESIGNATION_INSERT 14,'MANAGER'
		EXEC PR_DESIGNATION_INSERT 15,'CEO'

		SELECT * FROM DESIGNATION

	--Person 
		Create Proc PR_Person_Insert
			@FirstName		varchar(100),
			@LastName		varchar(100),
			@Salary			Decimal(8,2),
			@JoiningDate	Datetime,
			@DepartmentID	int,
			@DesignationID	int
		AS
		Begin
			INSERT INTO PERSON VALUES
			(@FirstName,		
			 @LastName,	
			 @Salary,		
			 @JoiningDate,
			 @DepartmentID,
			 @DesignationID)
		END	

		EXEC PR_Person_Insert 'RAHUL','ANSHU',56000,'1990-01-01',1,12
		EXEC PR_Person_Insert 'HARDIK','HINSU',18000,'1990-09-25',2,11
		EXEC PR_Person_Insert 'BHAVIN','KAMANI',25000,'1991-05-14',NULL,11
		EXEC PR_Person_Insert 'BHOOMI','PATEL',39000,'2014-02-20',1,13
		EXEC PR_Person_Insert 'ROHIT','RAJGOR',17000,'1990-07-23',2,15
		EXEC PR_Person_Insert 'PRIYA','MEHTA',25000,'1990-10-18',2,NULL
		EXEC PR_Person_Insert 'NEHA','TRIVEDI',18000,'2014-02-20',3,15

		SELECT * FROM PERSON
			
--UPDATE
	--PERSON
		CREATE PROC PR_PERSON_UPDATE
			@WORKERID INT,
			@SALARY   DECIMAL(8,2)
		AS
		BEGIN
			UPDATE PERSON
			SET SALARY=@SALARY
			WHERE WORKERID=@WORKERID
		END 
		
		EXEC PR_PERSON_UPDATE 105,20000
		SELECT * FROM PERSON

	--DEPARTMENT
		CREATE PROC PR_DEPARTMENT_UPDATE
			@DEPARTMENTID	INT,
			@DEPARTMENTNAME VARCHAR(100)
		AS
		BEGIN
			UPDATE DEPARTMENT
			SET DEPARTMENTNAME=@DEPARTMENTNAME
			WHERE DEPARTMENTID=@DEPARTMENTID
		END
		
		EXEC PR_DEPARTMENT_UPDATE 1,'ADMIN1'
		SELECT * FROM DEPARTMENT

	--DESIGNATION
		CREATE PROC PR_DESIGNATION_UPDATE
			@DESIGNATIONID	 INT,
			@DESIGNATIONNAME VARCHAR(100)
		AS
		BEGIN
			UPDATE DESIGNATION
			SET DESIGNATIONNAME=@DESIGNATIONNAME
			WHERE DESIGNATIONID=@DESIGNATIONID
		END
		
		EXEC PR_DESIGNATION_UPDATE 11,'JOBBER1'
		SELECT * FROM DESIGNATION

--DELETE
	--PERSON
		CREATE PROC PR_PERSON_DELETE
			@WORKERID	INT
		AS
		BEGIN
			DELETE FROM PERSON 
			WHERE WORKERID=@WORKERID
		END

		EXEC PR_PERSON_DELETE 106
		SELECT * FROM PERSON

	--DEPARTMENT
		CREATE PROC PR_DEPARTMENT_DELETE
			@DEPARTMENTID	INT
		AS
		BEGIN
			DELETE FROM DEPARTMENT 
			WHERE DEPARTMENTID=@DEPARTMENTID
		END

		EXEC PR_DEPARTMENT_DELETE 4
		SELECT * FROM DEPARTMENT

	--DESIGNATION
		CREATE PROC PR_DESIGNATION_DELETE
			@DESIGNATIONID	INT
		AS
		BEGIN
			DELETE FROM DESIGNATION 
			WHERE DESIGNATIONID=@DESIGNATIONID
		END

		EXEC PR_DESIGNATION_DELETE 14
		SELECT * FROM DESIGNATION
--2. All tables SelectAll (If foreign key is available than do write join and take columns on select list)
	--PERSON
		ALTER PROC PR_PERSON_SELECTALL
		AS
		BEGIN
			SELECT PERSON.WORKERID,
				   PERSON.FIRSTNAME,
				   PERSON.LASTNAME,
				   PERSON.SALARY,
				   PERSON.JOININGDATE,
				   DEPARTMENT.DEPARTMENTNAME,
				   DESIGNATION.DESIGNATIONNAME
			FROM PERSON LEFT OUTER JOIN DEPARTMENT 
			ON PERSON.DEPARTMENTID=DEPARTMENT.DEPARTMENTID
			LEFT OUTER JOIN DESIGNATION 
			ON PERSON.DESIGNATIONID=DESIGNATION.DESIGNATIONID	 
		END
		
		EXEC PR_PERSON_SELECTALL

	--DEPARTMENT
		CREATE PROC PR_DEPARTMENT_SELECTALL
		AS
		BEGIN
			SELECT DEPARTMENTID,DEPARTMENTNAME FROM DEPARTMENT
		END

		EXEC PR_DEPARTMENT_SELECTALL

	--DESIGNATION
		CREATE PROC PR_DESIGNATION_SELECTALL
		AS
		BEGIN
			SELECT DESIGNATIONID,DESIGNATIONNAME FROM DESIGNATION
		END
		
		EXEC PR_DESIGNATION_SELECTALL
--3. All tables SelectPK
	--PERSON
		CREATE PROC PR_PERSON_SELECTPK
			@WORKERID	INT
		AS
		BEGIN
			SELECT * FROM PERSON
			WHERE WORKERID=@WORKERID
		END

		EXEC PR_PERSON_SELECTPK 101

	--DEPARTMENT
		CREATE PROC PR_DEPARTMENT_SELECTPK
			@DEPARTMENTID	INT
		AS
		BEGIN
			SELECT * FROM DEPARTMENT
			WHERE DEPARTMENTID=@DEPARTMENTID
		END

		EXEC PR_DEPARTMENT_SELECTPK 1

	--DESIGNATION
		CREATE PROC PR_DESIGNATION_SELECTPK
			@DESIGNATIONID	INT
		AS
		BEGIN
			SELECT * FROM DESIGNATION
			WHERE DESIGNATIONID=@DESIGNATIONID
		END

		EXEC PR_DESIGNATION_SELECTPK 11
--4. Create Procedure that takes Department Name & Designation Name as Input and Returns a 
--table with Worker’s First Name, Salary, Joining Date & Department Name.
	ALTER PROC PR_PERSON_RETURNTABLE
		@DEPARTMENTNAME		VARCHAR(100),
		@DESIGNATIONNAME	VARCHAR(100)
	AS
	BEGIN
		SELECT P.FIRSTNAME,P.SALARY,P.JOININGDATE,D.DEPARTMENTNAME
		FROM PERSON P LEFT OUTER JOIN DEPARTMENT D
		ON P.DEPARTMENTID=D.DEPARTMENTID 
		LEFT OUTER JOIN DESIGNATION DE
		ON P.DESIGNATIONID=DE.DESIGNATIONID
		WHERE D.DEPARTMENTNAME=@DEPARTMENTNAME AND DE.DESIGNATIONNAME=@DESIGNATIONNAME
	END

	EXEC PR_PERSON_RETURNTABLE 'ADMIN1','WELDER'
--5. Create Procedure that takes FirstName as an input parameter and displays’ all the details of 
--the worker with their department & designation name.

--6. Create Procedure which displays department wise maximum, minimum & total salaries.