--1. Create INSERT, UPDATE & DELETE Stored Procedures for Person table.
--2. Create a trigger that fires on INSERT, UPDATE and DELETE operation on the Person table. For that,
--create a new table PersonLog to log (enter) all operations performed on the Person table.

--INSERT
CREATE TRIGGER TR_INSERT
ON PERSON
AFTER INSERT
AS
BEGIN
	DECLARE @PERSONID INT
	DECLARE @PERSONNAME VARCHAR(50)
	SELECT @PERSONID=PERSONID,@PERSONNAME=PERSONNAME FROM INSERTED
	INSERT INTO PERSONLOG VALUES(@PERSONID,@PERSONNAME,'INSERT',GETDATE())	
END 

INSERT INTO PERSON VALUES(101,'RUSHI','50000','2022-06-29','RAJKOT','19','2004-06-29')
INSERT INTO PERSON VALUES(102,'HIMANSHU','40000','2022-03-22','AHMEDABAD','18','2003-05-10')

SELECT * FROM PERSONLOG

--UPDATE
CREATE TRIGGER TR_UPDATE
ON PERSON
AFTER UPDATE
AS
BEGIN
	DECLARE @PERSONID INT
	DECLARE @PERSONNAME VARCHAR(50)
	SELECT @PERSONID=PERSONID,@PERSONNAME=PERSONNAME FROM INSERTED
	INSERT INTO PERSONLOG VALUES(@PERSONID,@PERSONNAME,'UPDATE',GETDATE())	
END

UPDATE PERSON SET CITY='AHMEDABAD' WHERE PERSONID=101

SELECT * FROM PERSONLOG

--DELETE
ALTER TRIGGER TR_DELETE
ON PERSON
AFTER DELETE
AS
BEGIN
	DECLARE @PERSONID INT
	DECLARE @PERSONNAME VARCHAR(50)
	SELECT @PERSONID=PERSONID,@PERSONNAME=PERSONNAME FROM DELETED
	INSERT INTO PERSONLOG VALUES(@PERSONID,@PERSONNAME,'DELETE',GETDATE())	
END

DELETE FROM PERSON WHERE PERSONID=102

SELECT * FROM PERSON
INSERT INTO PERSON VALUES(102,'HIMANSHU',30000,'2022-02-27','RAJKOT',19,'2004-05-26')
SELECT * FROM PERSONLOG

--3. Create an INSTEAD OF trigger that fires on INSERT, UPDATE and DELETE operation on the Person
--table. For that, log all operation performed on the Person table into PersonLog.


--4. Create DELETE trigger on PersonLog table, when we delete any record of PersonLog table it prints
--‘Record deleted successfully from PersonLog’.

CREATE TRIGGER TR_DELETE_MSG
ON PERSONLOG
AFTER DELETE
AS
BEGIN
	PRINT 'RECORD DELETED SUCCESSFULLY FROM PERSONLOG'
END

DELETE FROM PERSONLOG WHERE PLOGID=7

SELECT * FROM PERSONLOG
--5. Create INSERT trigger on person table, which calculates the age and update that age in Person
--table.