--Select All

CREATE PROCEDURE PR_MSTCITY_SELECTALL
AS
BEGIN
	SELECT	C.City_ID,
		    C.City_Name,
			C.Pincode,
			C.Remarks,
			S.State_name
	FROM MST_City C INNER JOIN MST_State S
	ON C.State_ID=S.State_ID
END	

EXEC PR_MSTCITY_SELECTALL

--2 INSERT

CREATE PROC PR_MSTCITY_INSERT
	@CITYID			INT,
	@CITYNAME		VARCHAR(250),
	@PINCODE		VARCHAR(6),
	@STATEID		INT,
	@REMARKS		VARCHAR(500)
AS
BEGIN
	INSERT INTO MST_City(City_ID,	
						 City_Name,	
						 Pincode,	
						 State_ID,	
						 Remarks)
	VALUES (@CITYID,	
			@CITYNAME,	
			@PINCODE,	
			@STATEID,	
			@REMARKS)
END	

exec PR_MSTCITY_INSERT 105,vadodara,360002,1,good
select * from MST_City
update MST_City set City_ID=5 where City_ID=105

--update

CREATE PROC PR_MSTCITY_UPDATE
	@CITYID			INT,
	@CITYNAME		VARCHAR(250),
	@PINCODE		VARCHAR(6),
	@STATEID		INT,
	@REMARKS		VARCHAR(500)
AS
BEGIN
	UPDATE MST_City
	SET City_ID=@CITYID,
		City_Name=@CITYNAME,
		Pincode=@PINCODE,	
		State_ID=@STATEID,	
		Remarks=@REMARKS
	WHERE City_ID=@CITYID
END

EXEC PR_MSTCITY_UPDATE 1,RAJKOT,360004,1,CLEAN
SELECT * FROM MST_City

--DELETE

CREATE PROC PR_MSTCITY_DELETE
	@CITYID  INT
AS
BEGIN
	DELETE FROM MST_City
	WHERE City_ID=@CITYID
END

EXEC PR_MSTCITY_DELETE 5
SELECT * FROM MST_City

--SELECTBYPK

CREATE PROC PR_MSTCITY_SELECTBYPK
	@CITYID  INT
AS
BEGIN
	SELECT * FROM MST_City
	WHERE City_ID=@CITYID
END

EXEC PR_MSTCITY_SELECTBYPK 1

--SELECTBYPINCODESTARTSWITH360

CREATE PROC PR_MSTCITY_SELECTBYPINCODESTARTSWITH360
AS
BEGIN
	SELECT * FROM MST_City
	WHERE PINCODE LIKE '360%'
END

EXEC PR_MSTCITY_SELECTBYPINCODESTARTSWITH360

--SELECTBYCITYNAMEPINCODE

ALTER PROC PR_MSTCITY_SELECTBYCITYNAMEPINCODE
	@CITYNAME    VARCHAR(250),
	@PINCODE     VARCHAR(6)
AS
BEGIN
	SELECT * FROM MST_City
	WHERE City_Name=@CITYNAME AND
		  Pincode=@PINCODE
END

EXEC PR_MSTCITY_SELECTBYCITYNAMEPINCODE RAJKOT,360004 

--SELECTBYREMARKS

CREATE PROC PR_MSTCITY_SELECTBYREMARKS
	@REMARKS	VARCHAR(500)
AS
BEGIN
	SELECT * FROM MST_City
	WHERE Remarks=@REMARKS
END

EXEC PR_MSTCITY_SELECTBYREMARKS GOOD

--SELECTBYSTATEID

CREATE PROC PR_MSTCITY_SELECTBYSTATEID
	@STATEID	int
AS
BEGIN
	SELECT * FROM MST_City
	WHERE State_ID=@STATEID
END

EXEC PR_MSTCITY_SELECTBYSTATEID 1

--SELECTBYSTATEIDCITYID

CREATE PROC PR_MSTCITY_SELECTBYSTATEIDCITYID
	@STATEID	INT,
	@CITYID		INT
AS
BEGIN
	SELECT * FROM MST_City
	WHERE State_ID=@STATEID AND City_ID=@CITYID
END

EXEC PR_MSTCITY_SELECTBYSTATEIDCITYID 1,1 