ALTER TRIGGER TR_INSERT
ON EMPMASTER
AFTER INSERT
AS
BEGIN
	PRINT 'RECORD ID INSERTED'
	SELECT * FROM INSERTED
END

INSERT INTO EMPMASTER VALUES(11,'XYZ','MALE','1990-02-25',35000,'RAJKOT')
SELECT * FROM EMPMASTER

ALTER TRIGGER TR_UPDATE
ON EMPMASTER
AFTER UPDATE
AS
BEGIN
	PRINT 'RECORD IS UPDATED'
	SELECT * FROM INSERTED
END

UPDATE EMPMASTER SET CITY='JAMNAGAR' WHERE EID=11

ALTER TRIGGER TR_DELETE
ON EMPMASTER
AFTER DELETE
AS
BEGIN
	PRINT 'RECORD IS DELETED'
	SELECT * FROM DELETED
END

DELETE FROM EMPMASTER WHERE EID=11
